name: Minimal check for Symfony installation (Backend/PHP part)

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: PHP version
        run: php -v

      - name: Composer version
        run: composer --version

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Check code style (config from phpcs.xml.dist)
        run: bin/console -V